### ISSUE TITLE
Why no support for article aliasses?

### ISSUE THREAD

**Issue by arno1979** [ausi/contao-slug-backport#5]
Thanks for the backport, really helpful!
I just have a quick question: Is there a reason why support for entries in tl_article is not included?

Thanks
Arno

**Comment by ausi** [comment]
Looks like tl_article and tl_form were added in a later commit in https://github.com/contao/contao/commit/c4cf7859e87f21e640edefb7a7d0dc2fa314152e . This is probably the reason I overlooked it.

**Comment by Aybee** [comment]
Will you fix this in the near future?

**Comment by ausi** [comment]
Can you please verify that the `dev-master` version works for `tl_form` and `tl_article`?

```
"ausi/contao-slug-backport": "dev-master",
```

After verification I can release a new version.

**Comment by Aybee** [comment]
Hallo ausi, die Aliase in tl_article funktionieren. Die Formular-Aliase nicht. Ich hatte Probleme bei der Installation von dev-master. Als erstes kam eine Fehlermeldung:
```
ERROR 500 Invalid repository data in /kunden/XXX/rp-hosting/5143106/6143106/typo3cms/XXX.de/vendor/composer/installed.json, packages could not be loaded: [Seld\JsonLint\ParsingException] "/kunden/XXX/rp-hosting/5143106/6143106/typo3cms/XXX.de/vendor/composer/installed.json" does not contain valid JSON Parse error on line 1534: ...s": { ---------------------^ Expected one of: 'STRING', '}'
```
Danach war die Installation von Contao zerschossen, Manager ging nur noch im abgesicherten Modus, Contao Auto-Reparatur nicht möglich, Kein Zugang zum BE. Ursprünglich lief PHP 7.2.11, habe dann 7.2.19 und 7.3.6 probiert, Installation blieb aber defekt. Spooky hat mir auf Slack geholfen, habe die vendor/composer/installed.json gelöscht und den Manager neu gestartet.

**Comment by Aybee** [comment]
Es scheint nicht an der dev-master gelegen zu haben. Näheres, warum der Fehler passiert ist, weiß auch niemand. Es bleibt dabei, dass tl_form noch nicht funktioniert.

**Comment by ausi** [comment]
We should change the default value as was done in https://github.com/contao/contao/commit/c4cf7859e87f21e640edefb7a7d0dc2fa314152e

The tl_form problem seems to be in Contao 4.7 too, probably because the jumpTo page isn’t saved when the alias is being generated.

**Comment by ausi** [comment]
Ticket for tl_form in Contao 4.7: contao/contao#571

**Comment by ausi** [comment]
Should be fixed now in version 1.0.5

**Comment by Aybee** [comment]
Thank you very much 👍
